AFTER_COUNTRY_CREATE = "Country create successfuly."
AFTER_CITY_CREATE = "City create successfuly."
AFTER_REGION_CREATE = "Region create successfuly."
NO_REGION_FOUND = "No regions found for the provided country IDs."
NO_CITIES_FOUND = "No cities found for the provided region IDs."
NO_SONG_FOUND = "No songs found for the given criteria."
NO_GENRES_FOUND = "No genres found for the given criteria."
NO_FUND_FOUND = "No fund found for the given criteria."
