"""change content len

Revision ID: eff25c9d3484
Revises: 093aff8a4065
Create Date: 2024-04-04 18:56:13.561404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "eff25c9d3484"
down_revision: Union[str, None] = "093aff8a4065"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "about",
        "content",
        existing_type=sa.VARCHAR(length=10000),
        type_=sa.String(length=30000),
        existing_nullable=False,
    )
    op.alter_column(
        "expedition",
        "content",
        existing_type=sa.VARCHAR(length=10000),
        type_=sa.String(length=30000),
        existing_nullable=False,
    )
    op.alter_column(
        "news",
        "content",
        existing_type=sa.VARCHAR(length=10000),
        type_=sa.String(length=30000),
        existing_nullable=False,
    )
    op.alter_column(
        "our_projects",
        "content",
        existing_type=sa.VARCHAR(length=10000),
        type_=sa.String(length=30000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "our_projects",
        "content",
        existing_type=sa.String(length=30000),
        type_=sa.VARCHAR(length=10000),
        existing_nullable=False,
    )
    op.alter_column(
        "news",
        "content",
        existing_type=sa.String(length=30000),
        type_=sa.VARCHAR(length=10000),
        existing_nullable=False,
    )
    op.alter_column(
        "expedition",
        "content",
        existing_type=sa.String(length=30000),
        type_=sa.VARCHAR(length=10000),
        existing_nullable=False,
    )
    op.alter_column(
        "about",
        "content",
        existing_type=sa.String(length=30000),
        type_=sa.VARCHAR(length=10000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
