"""add field to city

Revision ID: e6bbf7bbeb57
Revises: de8126b214ca
Create Date: 2024-03-26 21:42:05.058366

"""
from typing import Sequence, Union

from alembic import op
from fastapi_storages import FileSystemStorage
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType

storage = FileSystemStorage(path="static/media/cities")
# revision identifiers, used by Alembic.
revision: str = "e6bbf7bbeb57"
down_revision: Union[str, None] = "de8126b214ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cities", sa.Column("photo", FileType(storage=storage), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cities", "photo")
    # ### end Alembic commands ###
