"""validation for education info

Revision ID: c2444445cb93
Revises: ed8c3dfeff7b
Create Date: 2024-03-12 15:26:38.038254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "c2444445cb93"
down_revision: Union[str, None] = "ed8c3dfeff7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expedition_info",
        "title",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=70),
        existing_nullable=False,
    )
    op.alter_column(
        "expedition_info",
        "description",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=600),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expedition_info",
        "description",
        existing_type=sa.String(length=600),
        type_=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "expedition_info",
        "title",
        existing_type=sa.String(length=70),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
