"""add fund table and relation with song table

Revision ID: 379d6e499fef
Revises: 99cf242221d4
Create Date: 2024-02-16 15:14:29.967299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = '379d6e499fef'
down_revision: Union[str, None] = '99cf242221d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('song', sa.Column('fund_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'funds', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'fund_id')
    op.drop_table('funds')
    # ### end Alembic commands ###
