"""validation song

Revision ID: 093aff8a4065
Revises: e6bbf7bbeb57
Create Date: 2024-03-29 14:03:07.896225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "093aff8a4065"
down_revision: Union[str, None] = "e6bbf7bbeb57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "education_page",
        "description",
        existing_type=sa.VARCHAR(length=600),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "song",
        "song_description",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    op.alter_column(
        "song",
        "comment_map",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column("song", "photo1", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("song", "photo1", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "song",
        "comment_map",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "song",
        "song_description",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "education_page",
        "description",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=600),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
