"""enographic photo is not required

Revision ID: de8126b214ca
Revises: e0f1847518a2
Create Date: 2024-03-24 11:09:04.309740

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "de8126b214ca"
down_revision: Union[str, None] = "e0f1847518a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "song", "ethnographic_photo1", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "song", "ethnographic_photo1", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
