"""add eduction page tables and relationships

Revision ID: c6567fab9da4
Revises: 8e769970fc53
Create Date: 2024-02-12 04:29:17.278639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType
from fastapi_storages import FileSystemStorage


# revision identifiers, used by Alembic.
revision: str = "c6567fab9da4"
down_revision: Union[str, None] = "8e769970fc53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
storage1 = FileSystemStorage(path="static/media/calendar_and_ritual_categories")
storage2 = FileSystemStorage(path="static/media/song_subcategories")
storage3 = FileSystemStorage(path="static/media/education_page_song_genres")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_and_ritual_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("media", FileType(storage1), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("recommended_sources", sa.String(length=10000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "education_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("recommendations", sa.String(length=10000), nullable=True),
        sa.Column("recommended_sources", sa.String(length=10000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_subcategories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("media", FileType(storage2), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["main_category_id"],
            ["calendar_and_ritual_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "education_page_song_genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("media1", FileType(storage3), nullable=True),
        sa.Column("media2", FileType(storage3), nullable=True),
        sa.Column("media3", FileType(storage3), nullable=True),
        sa.Column("media4", FileType(storage3), nullable=True),
        sa.Column("media5", FileType(storage3), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.Column("sub_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["main_category_id"],
            ["calendar_and_ritual_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_category_id"],
            ["song_subcategories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_education_genre_association",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("education_genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["education_genre_id"],
            ["education_page_song_genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("song_id", "education_genre_id"),
    )
    op.drop_table("education_section")
    op.drop_column("footer", "qr_code_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "footer",
        sa.Column("qr_code_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "education_section",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(length=5000), autoincrement=False, nullable=True
        ),
        sa.Column("media1", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("media2", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("media3", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("media4", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("media5", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="education_section_pkey"),
    )
    op.drop_table("song_education_genre_association")
    op.drop_table("education_page_song_genres")
    op.drop_table("song_subcategories")
    op.drop_table("education_page")
    op.drop_table("calendar_and_ritual_categories")
    # ### end Alembic commands ###
