"""add projects table

Revision ID: 67625f5934df
Revises: 70f10d045a6e
Create Date: 2024-02-15 16:55:54.637101

"""

from typing import Sequence, Union

from alembic import op
from fastapi_storages import FileSystemStorage
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "67625f5934df"
down_revision: Union[str, None] = "70f10d045a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
storage = FileSystemStorage(path="static/media/our_projects")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "our_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("short_description", sa.String(length=120), nullable=False),
        sa.Column("preview_photo", FileType(storage), nullable=True),
        sa.Column("project_date", sa.Date(), nullable=True),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column("authors", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("editors", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("photographers", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("recording", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("our_projects")
    # ### end Alembic commands ###
