"""validation for payment, partners

Revision ID: 5304409cf611
Revises: 9b48d4984dc8
Create Date: 2024-03-11 18:22:54.352456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "5304409cf611"
down_revision: Union[str, None] = "9b48d4984dc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("partners", "photo", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "payment_details",
        "organization_name",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=75),
        nullable=False,
    )
    op.alter_column(
        "payment_details", "edrpou", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "payment_details",
        "bank",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=50),
        nullable=False,
    )
    op.alter_column(
        "payment_details",
        "info",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_details",
        "iban",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=34),
        nullable=False,
    )
    op.alter_column(
        "payment_details",
        "patreon_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "payment_details",
        "coffee_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    op.alter_column(
        "payment_details", "qr_code_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_details", "qr_code_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "payment_details",
        "coffee_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "payment_details",
        "patreon_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.alter_column(
        "payment_details",
        "iban",
        existing_type=sa.String(length=34),
        type_=sa.VARCHAR(length=250),
        nullable=True,
    )
    op.alter_column(
        "payment_details",
        "info",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_details",
        "bank",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=250),
        nullable=True,
    )
    op.alter_column(
        "payment_details", "edrpou", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "payment_details",
        "organization_name",
        existing_type=sa.String(length=75),
        type_=sa.VARCHAR(length=250),
        nullable=True,
    )
    op.alter_column("partners", "photo", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
