"""recommended source for education

Revision ID: 8d3d8cd4f4b4
Revises: d1aaed5f734c
Create Date: 2024-03-07 14:37:05.364979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d3d8cd4f4b4"
down_revision: Union[str, None] = "d1aaed5f734c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "calendar_and_ritual_categories",
        "recommended_sources",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=1000)),
        type_=sa.String(length=10000),
        nullable=False,
    )
    op.alter_column(
        "education_page",
        "recommended_sources",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=1000)),
        type_=sa.String(length=10000),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "education_page",
        "recommended_sources",
        existing_type=sa.String(length=10000),
        type_=postgresql.ARRAY(sa.VARCHAR(length=1000)),
        nullable=True,
    )
    op.alter_column(
        "calendar_and_ritual_categories",
        "recommended_sources",
        existing_type=sa.String(length=10000),
        type_=postgresql.ARRAY(sa.VARCHAR(length=1000)),
        nullable=True,
    )
    # ### end Alembic commands ###
