"""add map photo field

Revision ID: 45a1edbc8cf8
Revises: c6567fab9da4
Create Date: 2024-02-13 15:35:23.950979

"""

from typing import Sequence, Union

from alembic import op
from fastapi_storages import FileSystemStorage
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType

storage = FileSystemStorage(path="static/media/song")

# revision identifiers, used by Alembic.
revision: str = "45a1edbc8cf8"
down_revision: Union[str, None] = "c6567fab9da4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("song", sa.Column("map_photo", FileType(storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("song", "map_photo")
    # ### end Alembic commands ###
