"""initial about

Revision ID: 2937331c001c
Revises: 09a45b0fd024
Create Date: 2024-02-10 02:44:50.371073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2937331c001c"
down_revision: Union[str, None] = "09a45b0fd024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "about",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("about")
    # ### end Alembic commands ###
