"""add expeditions

Revision ID: 70f10d045a6e
Revises: 45a1edbc8cf8
Create Date: 2024-02-14 23:21:20.750702

"""

from typing import Sequence, Union

from alembic import op
from fastapi_storages import FileSystemStorage
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "70f10d045a6e"
down_revision: Union[str, None] = "45a1edbc8cf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
storage = FileSystemStorage(path="static/media/expedition")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expedition_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expedition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False, index=True),
        sa.Column(
            "short_description", sa.String(length=120), nullable=False, index=True
        ),
        sa.Column("map_photo", FileType(storage), nullable=True),
        sa.Column("preview_photo", FileType(storage), nullable=True),
        sa.Column("expedition_date", sa.Date(), nullable=True),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("editors", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("photographers", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("recording", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expedition_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expedition")
    op.drop_table("expedition_category")
    # ### end Alembic commands ###
