"""change title for about and change administrative code to uniq

Revision ID: e0f1847518a2
Revises: 24bb37e386da
Create Date: 2024-03-14 13:40:56.812378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType


# revision identifiers, used by Alembic.
revision: str = "e0f1847518a2"
down_revision: Union[str, None] = "24bb37e386da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "about",
        "title",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=60),
        existing_nullable=False,
    )
    op.alter_column(
        "cities",
        "administrative_code",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.create_unique_constraint(None, "cities", ["administrative_code"])
    op.alter_column(
        "footer",
        "email",
        existing_type=sa.VARCHAR(length=35),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "footer",
        "email",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=35),
        existing_nullable=False,
    )
    op.drop_constraint(None, "cities", type_="unique")
    op.alter_column(
        "cities",
        "administrative_code",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "about",
        "title",
        existing_type=sa.String(length=60),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
